# This is an **adapted** version of https://github.com/trento-project/wanda/blob/main/docker-compose.checks.yaml

name: tcsc

services:

  trento-checks:
    container_name: tcsc-trento-checks
    image: ${WANDA_REGISTRY:-registry.opensuse.org/devel/sap/trento/factory/containers/trento}/trento-checks:${WANDA_VERSION:-latest}
    labels:
      - com.suse.tcsc.stack=wanda
      - com.suse.tcsc.expected_state=exited
      - com.suse.tcsc.expected_volumes=tcsc_trento-checks
    volumes:
      - trento-checks:/usr/share/trento/checks
      
  wanda:
    image: ${WANDA_REGISTRY:-registry.opensuse.org/devel/sap/trento/factory/containers/trento}/trento-wanda:${WANDA_VERSION:-latest}
    container_name: tcsc-wanda
    labels:
      - com.suse.tcsc.stack=wanda
      - com.suse.tcsc.expected_state=running
      - com.suse.tcsc.expected_volumes=tcsc_trento-checks
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres/postgres
      SECRET_KEY_BASE: dummyS3cr3t
      AMQP_URL: amqp://wanda:wanda@rabbitmq
      CORS_ENABLED: "false"
      ACCESS_TOKEN_ENC_SECRET: ""
      JWT_AUTHENTICATION_ENABLED: "false"
    depends_on:
      - trento-checks
      - postgres
      - rabbitmq
    ports:
      - 4000:4000
    volumes:
      - trento-checks:/usr/share/trento/checks 
    entrypoint: /bin/sh -c "/app/bin/wanda eval 'Wanda.Release.init()' && /app/bin/wanda start"

  rabbitmq:
    image: rabbitmq:3.10.5-management-alpine
    container_name: tcsc-rabbitmq
    labels:
      - com.suse.tcsc.stack=wanda
      - com.suse.tcsc.expected_state=running
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: wanda
      RABBITMQ_DEFAULT_PASS: wanda

  postgres:
    image: postgres:latest
    container_name: tcsc-postgres
    labels:
      - com.suse.tcsc.stack=wanda
      - com.suse.tcsc.expected_state=running
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
      labels:
      - com.suse.tcsc.stack=wanda
  trento-checks:
      labels:
      - com.suse.tcsc.stack=wanda


