# This is an **adapted** version of https://github.com/trento-project/wanda/blob/main/docker-compose.checks.yaml

name: tcsc

services:

  trento-checks:
    container_name: tcsc-trento-checks
    image: ${CHECKS_URL}:${CHECKS_VERSION}
    labels:
      - com.suse.tcsc.stack=wanda
      - com.suse.tcsc.expected_state=exited
      - com.suse.tcsc.expected_volumes=tcsc_trento-checks
    volumes:
      - trento-checks:/usr/share/trento/checks

  wanda:
    image: ${WANDA_URL}:${WANDA_VERSION}
    container_name: tcsc-wanda
    labels:
      - com.suse.tcsc.stack=wanda
      - com.suse.tcsc.expected_state=running
      - com.suse.tcsc.expected_volumes=tcsc_trento-checks
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres/postgres
      SECRET_KEY_BASE: dummyS3cr3t
      AMQP_URL: amqp://wanda:wanda@rabbitmq
      CORS_ENABLED: "false"
      CATALOG_PATH: /app/catalog
      TOKEN_AUTHENTICATION_ENABLED: "false"
    depends_on:
      - trento-checks
      - postgres
      - rabbitmq
    ports:
      - 4000:4000
    entrypoint: ${ENTRYPOINT}
    # Old entrypoint for SUSE and OpenSUSE registry (until 2.0.0) and still used in the developers GitHub.
    # entrypoint: /bin/sh -c "/app/bin/wanda eval \"Wanda.Release.init()\" && /app/bin/wanda start"
    # Entrypoint for SUSE and OpenSUSE registry with 2.1.0.
    #entrypoint: [/usr/lib/wanda/bin/wanda, start]
    volumes:
      #- ./checks:/usr/share/trento/checks:ro
      - ${CHECK_DIR:-trento-checks}:/usr/share/trento/checks

  rabbitmq:
    # Keep versions in sync with
      # .github/workflows/ci.yaml
      # https://github.com/trento-project/helm-charts/blob/main/charts/trento-server/charts/rabbitmq/values.yaml
    image: rabbitmq:3.12.6-management-alpine # https://hub.docker.com/_/rabbitmq/tags
    container_name: tcsc-rabbitmq
    labels:
      - com.suse.tcsc.stack=wanda
      - com.suse.tcsc.expected_state=running
    ports:
      - 5676:5671
      - 5674:5672
      - 15674:15672
    environment:
      RABBITMQ_DEFAULT_USER: wanda
      RABBITMQ_DEFAULT_PASS: wanda

  postgres:
    # Keep versions in sync with
      # .github/workflows/ci.yaml
      # https://github.com/trento-project/helm-charts/blob/main/charts/trento-server/values.yaml
      # https://documentation.suse.com/sles-sap/trento/single-html/SLES-SAP-trento/SLES-SAP-trento.html#id-install-postgresql
    image: registry.suse.com/suse/postgres:17.5 # https://registry.suse.com/repositories/suse-postgres17?tag=17.5
    container_name: tcsc-postgres
    labels:
      - com.suse.tcsc.stack=wanda
      - com.suse.tcsc.expected_state=running
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    labels:
      - com.suse.tcsc.stack=wanda
  trento-checks:
      labels:
      - com.suse.tcsc.stack=wanda


