#!/bin/bash
set -e  # exits in called scripts must terminate this one


setup/install_wanda

if [ -n "${BUILD_LOCAL}" ] ; then
    setup/install_cmd_local
    setup/install_host_local
else
    setup/install_cmd
    setup/install_host
fi

# Bye.
echo -e '\ntcsc set up successfully!' 
exit 0

