#!/usr/bin/bash

function clean() {
    local text="${1}"
    text="${text//\"/}" ; text="${text//\\?/}"
    echo "${text}"
}


# List all checks Wanda knows.
count=0
while read -r id ; read -r description ; read -r premium ; read -r group ; read -r provider ; do

    # Remove double qoutes and control characters.
    id=$(clean "${id}")
    description=$(clean "${description}")
    group=$(clean "${group}")
    provider=$(clean "${provider}") ; provider="${provider//[\[\]]/}" ; provider="${provider//,/ }" 

    if [ "${1}" == '-s' ] ; then
        echo "${id} - ${description} "
    else    
        case "${premium}" in
                true)   check_type='premium'
                        ;;
                false)  check_type='community'
                        ;;
                *)      check_type='unknown'
                        ;;
        esac

        echo -e "${id} - ${description}\n           check:    ${check_type}\n           group:    ${group}\n           provider: ${provider}\n"
    fi

    (( count++ ))

done < <(./rabbiteer.py -r http://localhost:4000 ListChecks | jq -c '.items[] | (.id, .description, .premium, .group, .metadata.provider)' | paste)

echo -e "\n${count} checks available."

# Bye.
exit 0
