#!/bin/bash
set -e  # exits in called scripts must terminate this one

setup/uninstall_wanda
setup/uninstall_cmd
setup/uninstall_host
setup/uninstall_networks

# Bye.
echo -e '\ntcsc removed successfully!' 
exit 0

