#!/bin/bash

dump_source='/tmp/sbd_dumps'

# Currently we only support '-d * dump'.
case "${@}" in 
    -d\ *\ dump)
        if [ -e "${dump_source}" ] ; then
            device=$(sed 's/^-d *// ; s/ *dump.*$//' <<< "${@}")
            device="${device//\//\\\/}"   # escape / 
            sed -n "/==Dumping header on disk ${device}/,/==Header on disk ${device} is dumped/p" "${dump_source}"
        else
            echo "${dump_source} does not exist!" >&2
            exit 1
        fi            
        ;;
    *)
        echo "\"${@}\" not supported!"  >&2
        exit 1
        ;;
esac

exit 0

