#!/bin/bash

env > log

# Set machine id.
echo "${MACHINE_ID}" > /etc/machine-id

# Extract files from packed supportconfig.
supportconfig="${SUPPORTCONFIG}"
supportconfig_dir="${SUPPORTCONFIG%.*}"
tar xf "${supportconfig}"
./split-supportconfig "${supportconfig_dir}/etc.txt" "${supportconfig_dir}/sysconfig.txt"

# Copy files from supportconfig into root fs.
mkdir /etc/corosync/
cp /rootfs/etc/corosync/corosync.conf /etc/corosync/
cp /rootfs/etc/sysconfig/sbd /etc/sysconfig/

# Start Prometheus Node Exporter (NOT NEEDED)
# /usr/bin/node_exporter &

# Start Trento agent
trento-agent start --config=/sc/agent-config.yaml 2> /var/log/trento-agent




