---
- name: Install required software
  hosts: all
  remote_user: root
  #become: true
  any_errors_fatal: true

  tasks:

    # - name: Patterns base
    #   zypper:
    #     name:
    #       - base
    #     type: pattern
    #     force: yes

    - name: Required packages
      zypper:
        name: 
          - docker
          #- docker-compose-switch
          - python3-docker-compose      # switch to pip?
          - python3-docker              # switch to pip?
          - git
        type: package

    - name: Start and enable docker daemon
      systemd:
        name: docker
        state: started
        enabled: true
