#!/bin/bash

echo
echo 'Remove command containers'
echo '-------------------------'
containers=$(docker ps -a --no-trunc --format="{{.ID}}" --filter label=com.suse.tcsc.stack=cmd | sort -u)
while read container ; do
    [ -z "${container}" ] && continue
    echo "Deleting container: ${container}"
    docker container rm -fv "${container}" 
done <<< "${containers}" 

echo
echo 'Remove command images'
echo '---------------------'
images=$(docker images --no-trunc --format="{{.ID}}" --filter label=com.suse.tcsc.stack=cmd | sort -u)
while read image ; do
    [ -z "${image}" ] && continue
    echo "Deleting image: ${image}"
    docker image rm -f "${image}" 
done <<< "${images}" 

echo
echo 'Remove command volumes'
echo '----------------------'
volumes=$(docker volume ls --format="{{.Mounts}}" --filter label=com.suse.tcsc.stack=cmd | sort -u)
while read volume ; do
    [ -z "${volume}" ] && continue
    echo "Deleting volume: ${volume}"
    docker volume rm -f "${volume}" 
done <<< "${volumes}" 

